import { useState, useMemo } from 'react';
import { Search, AlertTriangle, Send, HelpCircle, Link, CheckCircle, XCircle, RotateCcw, Clock, Shield } from 'lucide-react';
import { ACTIONS } from '../gameState';
import logsData from '../data/cloudtrail_logs.json';

const EVENT_COLOR = {
  RunInstances: '#ef4444',
  DeleteTrail: '#ef4444',
  AssumeRole: '#f59e0b',
  CreateSecurityGroup: '#f59e0b',
  PutObject: '#f59e0b',
  ConsoleLogin: '#94a3b8',
  ListBuckets: '#94a3b8',
  DescribeInstances: '#94a3b8',
  GetCallerIdentity: '#94a3b8',
};

// Key events for the timeline strip (chronological subset)
const TIMELINE_EVENTS = [
  { time: '09:12', event: 'GetCallerIdentity', color: '#94a3b8', icon: '🔍', label: 'Recon' },
  { time: '09:14', event: 'ListBuckets', color: '#94a3b8', icon: '🗂️', label: 'Enum' },
  { time: '09:21', event: 'AssumeRole ×1', color: '#f59e0b', icon: '🎭', label: 'Pivot 1' },
  { time: '09:22', event: 'AssumeRole ×2', color: '#f59e0b', icon: '🔗', label: 'Pivot 2' },
  { time: '09:23', event: 'RunInstances', color: '#ef4444', icon: '💣', label: 'Impact' },
  { time: '09:31', event: 'PutObject', color: '#f59e0b', icon: '📤', label: 'Exfil' },
  { time: '09:44', event: 'DeleteTrail', color: '#ef4444', icon: '🗑️', label: 'Cover' },
];

// Attack chain nodes — shown in scrambled order, must be placed in correct order
const CHAIN_NODES = [
  {
    id: 'cred',
    order: 1,
    icon: '🔑',
    title: 'Credential Theft',
    desc: 'Permanent IAM key AKIAIOSFODNN7DEV01A3 exfiltrated from developer workstation',
    color: '#ef4444',
  },
  {
    id: 'recon',
    order: 2,
    icon: '🔭',
    title: 'Initial Reconnaissance',
    desc: 'GetCallerIdentity + ListBuckets executed from 185.220.101.47 to enumerate AWS environment',
    color: '#f59e0b',
  },
  {
    id: 'role1',
    order: 3,
    icon: '🎭',
    title: 'First Role Pivot',
    desc: 'AssumeRole → AutomationServiceRole — ASIA session token generated, original IP masked',
    color: '#f59e0b',
  },
  {
    id: 'role2',
    order: 4,
    icon: '🔗',
    title: 'Role Chaining',
    desc: 'AssumeRole → DBSyncServiceRole — second lateral movement, elevated EC2 permissions acquired',
    color: '#f59e0b',
  },
  {
    id: 'exec',
    order: 5,
    icon: '💣',
    title: 'Impact: RunInstances',
    desc: 'Malicious EC2 instance launched via ec2.amazonaws.com endpoint (source IP no longer attacker\'s)',
    color: '#ef4444',
  },
  {
    id: 'exfil',
    order: 6,
    icon: '📤',
    title: 'Data Exfiltration',
    desc: 'PutObject to staging S3 bucket — sensitive corporate data written for remote retrieval',
    color: '#ef4444',
  },
];

// Scrambled display order
const SCRAMBLED = [3, 5, 1, 6, 2, 4].map(i => CHAIN_NODES[i - 1]);

const HINTS = [
  'The RunInstances event shows ec2.amazonaws.com as source IP. That\'s not the attacker — it\'s an AWS-internal endpoint. Look for an AssumeRole event BEFORE this call.',
  'Temporary credentials (ASIA...) are generated by AssumeRole. Trace the sessionContext backwards to find which permanent AKIA... credential originally requested them.',
  'The chain is: stolen permanent key → recon → AssumeRole (first pivot) → AssumeRole (second pivot) → RunInstances. The IP only appears in the events before the first AssumeRole.',
];

export default function Phase3Logs({ state, dispatch, addToast }) {
  const [search, setSearch] = useState('');
  const [expanded, setExpanded] = useState(null);
  const [submitIp, setSubmitIp] = useState('');
  const [submitKey, setSubmitKey] = useState('');
  const [submitRole, setSubmitRole] = useState('');
  const [wrongModal, setWrongModal] = useState(false);
  const [wrongMsg, setWrongMsg] = useState('');
  const hintsUsed = state.hintsUsed?.p3 || 0;

  // Attack chain state
  const [chainOrder, setChainOrder] = useState([]); // array of node ids in placed order
  const [chainResult, setChainResult] = useState(null); // null | 'correct' | 'wrong'
  const [chainAttempts, setChainAttempts] = useState(0);

  const filtered = useMemo(() => {
    const q = search.toLowerCase();
    if (!q) return logsData;
    return logsData.filter(log =>
      log.eventName.toLowerCase().includes(q) ||
      log.sourceIPAddress.toLowerCase().includes(q) ||
      (log.userIdentity?.accessKeyId || '').toLowerCase().includes(q) ||
      (log.userIdentity?.userName || '').toLowerCase().includes(q) ||
      (log.requestParameters?.roleArn || '').toLowerCase().includes(q)
    );
  }, [search]);

  const handleSubmit = () => {
    dispatch({ type: ACTIONS.SUBMIT_INVESTIGATION, payload: { ip: submitIp, apiKey: submitKey, roleArn: submitRole } });
    const ipC = submitIp.trim() === '185.220.101.47';
    const keyC = submitKey.trim() === 'AKIAIOSFODNN7DEV01A3';
    const roleC = submitRole.trim() === 'arn:aws:iam::123456789012:role/AutomationServiceRole';
    if (!ipC || !keyC || !roleC) {
      let err = 'One or more attribution fields are incorrect.';
      if (!ipC && submitIp.trim() === 'ec2.amazonaws.com') {
        err = 'Trap Triggered: The sourceIPAddress in the RunInstances event is ec2.amazonaws.com — an AWS-internal endpoint. Because a Role was assumed, the original attacker IP is masked. Trace the sessionContext backwards through the AssumeRole chain.';
      } else if (!keyC && submitKey.trim().startsWith('ASIA')) {
        err = 'Trap Triggered: ASIA... is a temporary session token generated by AssumeRole. The investigation requires the original permanent root credential (AKIA...) that was stolen and used to initiate the chain.';
      } else if (!roleC) {
        err = 'The Execution Role ARN is incorrect. Find the final Role ARN that actually issued the RunInstances call — this is the role whose AssumeRole event precedes the RunInstances timestamp.';
      }
      setWrongMsg(err);
      setWrongModal(true);
    }
  };

  const handleUseHint = () => {
    if (hintsUsed >= 3) return;
    dispatch({ type: ACTIONS.USE_HINT, payload: { phase: 'p3' } });
    addToast({ type: 'info', title: `Hint ${hintsUsed + 1}/3 Unlocked`, message: '−5 Admissibility' });
  };

  // Chain reconstruction handlers
  const handleChainNodeClick = (nodeId) => {
    if (chainResult === 'correct') return;
    setChainOrder(prev => {
      if (prev.includes(nodeId)) return prev.filter(id => id !== nodeId);
      return [...prev, nodeId];
    });
    setChainResult(null);
  };

  const handleChainSubmit = () => {
    setChainAttempts(n => n + 1);
    const correctOrder = CHAIN_NODES.map(n => n.id);
    const isCorrect = chainOrder.length === correctOrder.length &&
      chainOrder.every((id, i) => id === correctOrder[i]);
    if (isCorrect) {
      setChainResult('correct');
      dispatch({ type: ACTIONS.COMPLETE_ATTACK_CHAIN });
      addToast({ type: 'success', title: 'Attack Chain Verified', message: 'Full attack path correctly reconstructed.' });
    } else {
      setChainResult('wrong');
      dispatch({ type: ACTIONS.ATTACK_CHAIN_WRONG });
      addToast({ type: 'error', title: 'Chain Order Incorrect', message: '−10 Admissibility. Review the event timestamps and AssumeRole context.' });
    }
  };

  const handleChainReset = () => {
    setChainOrder([]);
    setChainResult(null);
  };

  return (
    <div style={{ padding: '1.5rem 2rem', minHeight: 'calc(100vh - 52px)', display: 'flex', flexDirection: 'column' }}>
      <div className="flex justify-between items-start mb-4">
        <div>
          <h1 className="text-xl font-bold mb-0.5">Phase 3: Log Analysis & Attribution</h1>
          <p className="text-sm mb-3" style={{ color: 'var(--color-text-muted)', lineHeight: 1.6 }}>
            You must reconstruct the attack sequence and attribute the breach to its true source.
            First, arrange the <strong>Attack Chain Nodes</strong> below in chronological order.
            Then, find the <strong>RunInstances</strong> event in the CloudTrail logs, trace the assumed roles backwards to find the compromised root credential, and submit your findings in the <strong>Attribution</strong> panel on the right.
          </p>
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '0.5rem' }}>
          {state.gameMode === 'Guided' && (
            <button className="btn btn-ghost" style={{ padding: '0.25rem 0.5rem', fontSize: '0.75rem' }} onClick={handleUseHint} disabled={hintsUsed >= 3}>
              <HelpCircle size={14} /> Request Hint ({3 - hintsUsed} left)
            </button>
          )}
        </div>
      </div>

      {hintsUsed > 0 && (
        <div className="card mb-4" style={{ background: 'rgba(99,102,241,0.1)', borderColor: 'rgba(99,102,241,0.3)' }}>
          <div className="flex items-center gap-2 mb-2" style={{ color: '#818cf8' }}>
            <HelpCircle size={16} />
            <span className="font-bold text-sm">Active Hints</span>
          </div>
          <ul className="text-sm space-y-2" style={{ color: 'var(--color-text)', paddingLeft: '1.5rem', listStyleType: 'disc' }}>
            {HINTS.slice(0, hintsUsed).map((hint, idx) => (
              <li key={idx} dangerouslySetInnerHTML={{ __html: hint }} />
            ))}
          </ul>
        </div>
      )}

      {/* ── TIMELINE STRIP ── */}
      <div className="card mb-4" style={{ background: '#080c14', border: '1px solid var(--color-border)', padding: '0.85rem 1rem' }}>
        <div className="flex items-center gap-2 mb-3">
          <Clock size={13} style={{ color: '#a5b4fc' }} />
          <span className="text-xs font-semibold uppercase tracking-wider" style={{ color: '#a5b4fc' }}>CloudTrail Event Timeline — Examination Phase (Lec 5 §7.3)</span>
        </div>
        <div style={{ position: 'relative', paddingBottom: '1.5rem' }}>
          {/* Baseline */}
          <div style={{ position: 'absolute', left: 0, right: 0, top: '1.2rem', height: 2, background: 'linear-gradient(to right, #1e2130, #4f46e5 20%, #ef4444 80%, #1e2130)' }} />
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '0.25rem' }}>
            {TIMELINE_EVENTS.map((ev, i) => (
              <div key={i} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', flex: 1 }}>
                <div style={{ fontSize: '0.65rem', color: 'var(--color-text-dim)', marginBottom: '0.3rem', fontFamily: 'monospace' }}>{ev.time}</div>
                <div style={{
                  width: 28, height: 28, borderRadius: '50%', zIndex: 1,
                  background: `${ev.color}22`, border: `2px solid ${ev.color}`,
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: '0.75rem', boxShadow: `0 0 8px ${ev.color}44`,
                }}>{ev.icon}</div>
                <div style={{ fontSize: '0.6rem', color: ev.color, fontWeight: 600, marginTop: '0.3rem', textAlign: 'center', lineHeight: 1.2 }}>{ev.label}</div>
                <div style={{ fontSize: '0.58rem', color: 'var(--color-text-dim)', textAlign: 'center', marginTop: '0.1rem' }}>{ev.event}</div>
              </div>
            ))}
          </div>
        </div>
        <div className="text-xs" style={{ color: 'var(--color-text-dim)', fontStyle: 'italic' }}>
          ⚠️ Note: The attacker’s true IP is only visible in events <em>before</em> the first AssumeRole pivot. After that, the source becomes an AWS internal endpoint.
        </div>
      </div>

      {/* Main 2-col layout: log viewer + attribution */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 360px', gap: '1.5rem', marginBottom: '1.5rem', alignItems: 'flex-start' }}>

        {/* Left Column */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          {/* Log viewer */}
          <div className="card" style={{ padding: 0, overflow: 'hidden', display: 'flex', flexDirection: 'column', height: '400px' }}>
          <div style={{ padding: '0.75rem 1rem', borderBottom: '1px solid var(--color-border)', display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
            <Search size={14} style={{ color: 'var(--color-text-dim)', flexShrink: 0 }} />
            <input
              className="input"
              style={{ border: 'none', background: 'transparent', padding: 0, fontFamily: 'JetBrains Mono, monospace' }}
              placeholder="Search by IP, Event Name, API Key, Role ARN..."
              value={search}
              onChange={e => setSearch(e.target.value)}
            />
            <span className="text-xs font-mono" style={{ color: 'var(--color-text-dim)', flexShrink: 0 }}>
              {filtered.length}/{logsData.length}
            </span>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '130px 160px 1fr 150px', padding: '0.35rem 1rem', borderBottom: '1px solid var(--color-border)', background: 'var(--color-bg)' }}>
            {['Time (UTC)', 'Event', 'Source IP', 'Identity Type'].map(h => (
              <div key={h} className="text-xs font-semibold uppercase tracking-wider" style={{ color: 'var(--color-text-dim)' }}>{h}</div>
            ))}
          </div>

          <div style={{ overflowY: 'auto', flex: 1 }}>
            {filtered.map(log => {
              const isExp = expanded === log.id;
              const color = EVENT_COLOR[log.eventName] || '#94a3b8';
              return (
                <div key={log.id} className="log-row" style={{ borderBottom: '1px solid var(--color-border)' }}>
                  <div
                    style={{ display: 'grid', gridTemplateColumns: '130px 160px 1fr 150px', padding: '0.55rem 1rem', cursor: 'pointer' }}
                    onClick={() => setExpanded(isExp ? null : log.id)}
                  >
                    <div className="font-mono text-xs" style={{ color: 'var(--color-text-muted)' }}>
                      {log.eventTime.split('T')[1].replace('Z', '')}
                    </div>
                    <div className="font-mono text-xs font-medium" style={{ color }}>{log.eventName}</div>
                    <div className="font-mono text-xs truncate" style={{ color: 'var(--color-text-muted)' }}>{log.sourceIPAddress}</div>
                    <div className="font-mono text-xs truncate" style={{ color: 'var(--color-text-dim)' }}>{log.userIdentity?.type}</div>
                  </div>
                  {isExp && (
                    <div style={{ padding: '0 1rem 0.75rem', background: 'var(--color-bg)' }}>
                      <pre className="font-mono text-xs p-3 rounded overflow-auto" style={{
                        background: '#060910', border: '1px solid var(--color-border)',
                        color: '#e0e7ff', maxHeight: 240,
                      }}>
                        {JSON.stringify(log, null, 2)}
                      </pre>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>

          {/* ── ATTACK CHAIN RECONSTRUCTION ── */}
      <div className="card" style={{ border: `1px solid ${state.attackChainCompleted ? 'rgba(34,197,94,0.4)' : 'rgba(99,102,241,0.4)'}` }}>
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <Link size={15} style={{ color: state.attackChainCompleted ? '#22c55e' : 'var(--color-primary)' }} />
            <span className="font-semibold text-sm">Attack Chain Reconstruction</span>
            {state.attackChainCompleted
              ? <span className="badge badge-success">VERIFIED</span>
              : <span className="badge badge-primary">REQUIRED</span>
            }
          </div>
          <div className="flex items-center gap-2">
            {!state.attackChainCompleted && (
              <button className="btn btn-ghost" style={{ fontSize: '0.7rem', padding: '0.2rem 0.5rem' }} onClick={handleChainReset}>
                <RotateCcw size={12} /> Reset
              </button>
            )}
          </div>
        </div>
        <p className="text-xs mb-4" style={{ color: 'var(--color-text-muted)', lineHeight: 1.6 }}>
          Using your CloudTrail analysis, reconstruct the complete attack chain in chronological order. Click the event tiles in the correct sequence (1 → 6), then submit for validation.
        </p>

        {/* Placed chain so far */}
        {chainOrder.length > 0 && (
          <div className="mb-4">
            <div className="text-xs font-semibold mb-2" style={{ color: 'var(--color-text-dim)' }}>Your Chain (click placed items to remove):</div>
            <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', alignItems: 'center' }}>
              {chainOrder.map((id, idx) => {
                const node = CHAIN_NODES.find(n => n.id === id);
                return (
                  <div key={id} style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                    <div
                      onClick={() => !state.attackChainCompleted && handleChainNodeClick(id)}
                      style={{
                        padding: '0.3rem 0.6rem', borderRadius: 6, fontSize: '0.7rem',
                        background: `${node.color}18`, border: `1px solid ${node.color}55`,
                        color: node.color, cursor: state.attackChainCompleted ? 'default' : 'pointer',
                        display: 'flex', alignItems: 'center', gap: '0.3rem',
                      }}
                    >
                      <span style={{ opacity: 0.6, fontWeight: 700 }}>{idx + 1}.</span>
                      <span>{node.icon}</span>
                      <span className="font-semibold">{node.title}</span>
                    </div>
                    {idx < chainOrder.length - 1 && <span style={{ color: 'var(--color-text-dim)', fontSize: '0.8rem' }}>→</span>}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Node tiles */}
        <div id="attack-chain">
        {!state.attackChainCompleted && (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.6rem', marginBottom: '1rem' }}>
            {SCRAMBLED.map(node => {
              const placed = chainOrder.includes(node.id);
              const placedIdx = chainOrder.indexOf(node.id);
              return (
                <div
                  key={node.id}
                  onClick={() => handleChainNodeClick(node.id)}
                  style={{
                    padding: '0.75rem', borderRadius: 8, cursor: 'pointer',
                    background: placed ? `${node.color}18` : 'var(--color-bg)',
                    border: `1px solid ${placed ? node.color : 'var(--color-border)'}`,
                    opacity: placed ? 0.5 : 1,
                    transition: 'all 0.15s',
                    position: 'relative',
                  }}
                  className="log-row"
                >
                  {placed && (
                    <div style={{
                      position: 'absolute', top: 6, right: 6,
                      width: 18, height: 18, borderRadius: '50%',
                      background: node.color, color: 'white',
                      fontSize: '0.65rem', fontWeight: 700,
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                    }}>{placedIdx + 1}</div>
                  )}
                  <div className="text-lg mb-1">{node.icon}</div>
                  <div className="font-semibold text-xs mb-1" style={{ color: placed ? node.color : 'var(--color-text)' }}>{node.title}</div>
                  <div className="text-xs" style={{ color: 'var(--color-text-dim)', lineHeight: 1.5 }}>{node.desc}</div>
                </div>
              );
            })}
          </div>
        )}

        {/* Completed state */}
        {state.attackChainCompleted && (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: '0.5rem' }}>
            {CHAIN_NODES.map((node, idx) => (
              <div key={node.id} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.25rem' }}>
                {idx > 0 && <div style={{ width: '100%', height: 2, background: '#22c55e', opacity: 0.4, marginBottom: 2 }} />}
                <div style={{ padding: '0.5rem', borderRadius: 6, background: 'rgba(34,197,94,0.1)', border: '1px solid rgba(34,197,94,0.3)', textAlign: 'center', width: '100%' }}>
                  <div className="text-lg mb-1">{node.icon}</div>
                  <div className="font-semibold text-xs" style={{ color: '#86efac' }}>{node.title}</div>
                </div>
              </div>
            ))}
          </div>
        )}
        </div>

        {/* Chain result feedback */}
        {chainResult === 'wrong' && (
          <div className="p-3 rounded mb-3 text-xs" style={{ background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.3)', color: '#fca5a5', lineHeight: 1.6 }}>
            <strong className="block mb-1">⚠ Incorrect Chain Order (−10 Admissibility, attempt #{chainAttempts})</strong>
            Recall that the attacker's IP only appears in pre-pivot events. AssumeRole events break the direct IP attribution. The chain starts with permanent credential usage, not with the final impact event.
          </div>
        )}

        {!state.attackChainCompleted && chainOrder.length === 6 && chainResult !== 'correct' && (
          <button className="btn btn-primary" onClick={handleChainSubmit}>
            <CheckCircle size={14} /> Validate Chain Order
          </button>
        )}
        {!state.attackChainCompleted && chainOrder.length < 6 && (
          <div className="text-xs" style={{ color: 'var(--color-text-dim)' }}>
            {6 - chainOrder.length} event{6 - chainOrder.length !== 1 ? 's' : ''} remaining — click tiles above to place them in your chain
          </div>
        )}
      </div>

      
        </div>

        {/* Attribution panel & Anti-Forensics callout */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>

          {/* Anti-Forensics callout */}
          <div className="card" style={{ background: 'rgba(239,68,68,0.06)', border: '1px solid rgba(239,68,68,0.25)' }}>
            <div className="flex items-center gap-2 mb-2">
              <Shield size={13} style={{ color: '#ef4444' }} />
              <span className="text-xs font-semibold" style={{ color: '#fca5a5' }}>Anti-Forensics Detected: Role Chaining (Lec 5 §7.4)</span>
            </div>
            <div className="text-xs" style={{ color: 'var(--color-text-muted)', lineHeight: 1.7 }}>
              The attacker used <span style={{ color: '#fca5a5' }}>AssumeRole</span> as an anti-forensic technique — similar to how HTTPS hides payload contents from network inspection,{' '}
              role chaining hides the caller’s true IP address. After each pivot, the <code style={{ color: '#86efac' }}>sourceIPAddress</code> field changes to an AWS internal endpoint.{' '}
              The counter-technique: trace the <code style={{ color: '#86efac' }}>sessionContext.sessionIssuer</code> chain backwards to the original permanent credential.
            </div>
          </div>

          <div id="attribution-panel" className="card">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <AlertTriangle size={15} style={{ color: '#ef4444' }} />
                <span className="font-semibold text-sm">Root Cause Attribution</span>
              </div>
            </div>

            {/* Correlative Analysis note */}
            <div className="p-2 rounded mb-3 text-xs" style={{ background: 'rgba(99,102,241,0.06)', border: '1px solid rgba(99,102,241,0.2)', color: '#c7d2fe', lineHeight: 1.6 }}>
              <strong style={{ display: 'block', marginBottom: '0.2rem' }}>Correlative Analysis (Lec 13)</strong>
              CloudTrail is <em>external</em> to the compromised instance — it cannot be tampered with from within the VM. This makes it more trustworthy than the instance’s own logs, which a rootkit could have modified.
              <br /><br />
              <strong style={{ display: 'block', marginBottom: '0.2rem' }}>☁️ Cloud Log Completeness (Lec 26)</strong>
              Cloud environments separate management logs from data-plane logs. If data events (like S3 object reads/writes) aren't explicitly enabled, your forensic timeline will have critical gaps.
            </div>

            <p className="text-xs mb-4" style={{ color: 'var(--color-text-muted)', lineHeight: 1.6 }}>
              Do NOT submit intermediate pivot IPs or temporary tokens. Find the original AKIA credential and the true external attacker IP.
            </p>

            <div className="space-y-3">
              <div>
                <label className="text-xs font-semibold block mb-1" style={{ color: 'var(--color-text-muted)' }}>
                  True Attacker Source IP
                </label>
                <input className="input" placeholder="Not the AWS endpoint..." value={submitIp} onChange={e => setSubmitIp(e.target.value)} />
              </div>
              <div>
                <label className="text-xs font-semibold block mb-1" style={{ color: 'var(--color-text-muted)' }}>
                  Execution Role ARN
                </label>
                <input className="input font-mono text-xs" placeholder="arn:aws:iam::..." value={submitRole} onChange={e => setSubmitRole(e.target.value)} />
              </div>
              <div>
                <label className="text-xs font-semibold block mb-1" style={{ color: 'var(--color-text-muted)' }}>
                  Root Compromised IAM Key ID
                </label>
                <input className="input font-mono text-xs" placeholder="AKIA..." value={submitKey} onChange={e => setSubmitKey(e.target.value)} />
              </div>
            </div>

            <button
              className="btn btn-primary mt-5 w-full justify-center"
              onClick={handleSubmit}
              disabled={!submitIp || !submitKey || !submitRole}
            >
              <Send size={14} /> Submit Final Report
            </button>
          </div>

          {/* Quick reference */}
          <div className="card" style={{ background: 'rgba(99,102,241,0.05)', border: '1px solid rgba(99,102,241,0.2)' }}>
            <div className="text-xs font-semibold mb-2" style={{ color: '#a5b4fc' }}>📚 IAM Key Prefixes</div>
            <div className="space-y-1.5 font-mono text-xs" style={{ color: 'var(--color-text-dim)' }}>
              <div><span style={{ color: '#22c55e' }}>AKIA...</span> — Permanent long-term key</div>
              <div><span style={{ color: '#f59e0b' }}>ASIA...</span> — Temporary session token</div>
              <div><span style={{ color: '#64748b' }}>AROA...</span> — Role assumed principal</div>
            </div>
            <div className="text-xs mt-3 pt-3" style={{ borderTop: '1px solid var(--color-border)', color: 'var(--color-text-dim)' }}>
              sessionContext.sessionIssuer shows the role ARN that generated a temporary token.
            </div>
          </div>
        </div>
      </div>


      {/* Wrong submission modal */}
      {wrongModal && (
        <div className="modal-overlay">
          <div className="modal">
            <div className="text-4xl text-center mb-3">🔍</div>
            <h2 className="text-lg font-bold text-center mb-2" style={{ color: '#ef4444' }}>Forensic Attribution Failed</h2>
            <p className="text-sm mb-4 font-mono p-3 rounded" style={{ background: '#2a1215', color: '#fca5a5', border: '1px solid #7f1d1d', lineHeight: 1.7 }}>
              {wrongMsg}
            </p>
            <div className="p-3 rounded mb-4 text-sm" style={{ background: 'rgba(99,102,241,0.08)', border: '1px solid rgba(99,102,241,0.2)', color: '#c7d2fe' }}>
              <strong>Analyst Guidance:</strong>
              <ul className="mt-2 space-y-2 text-xs list-disc pl-4" style={{ opacity: 0.9 }}>
                <li>A <code>RunInstances</code> call via an IAM Role displays the AWS service endpoint, not the user IP.</li>
                <li>Temporary creds start with <code>ASIA...</code>. Permanent IAM keys start with <code>AKIA...</code>.</li>
                <li>Find the <code>AssumeRole</code> event preceding the attack. Match <code>sessionContext.sessionIssuer.arn</code> to the role ARN.</li>
              </ul>
            </div>
            <button className="btn btn-primary w-full" onClick={() => setWrongModal(false)}>
              Re-evaluate Timelines (−15 Admissibility)
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
